apiVersion: v1
kind: Secret
metadata:
  name: droneflow-secret
  namespace: droneflow
type: Opaque
# If I would use data instead of stringData, I would need to base64 encode the values
stringData:
  MONGO_USERNAME: "admin"
  MONGO_PASSWORD: "pass"
