apiVersion: v1
kind: Secret
metadata:
  name: droneflow-secret
  namespace: droneflow
type: Opaque
# If I would use data instead of stringData, I would need to base64 encode the values
stringData:
  MONGO_USERNAME: "root"
  MONGO_PASSWORD: "root"
  MONGODB_URI: "mongodb://root:root@mongodb:27017/?authSource=admin"
