name: documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.push.base.ref }}

      - name: Configure Git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: quarkdown-labs/setup-quarkdown@v1

      - name: Build Project Overview Statement
        run: quarkdown c documentation/pos/main.qd --pdf --out ./documentation/out --out-name pos

      - name: Build Stakeholder
        run: quarkdown c documentation/stakeholder/main.qd --pdf --out ./documentation/out --out-name stakeholder

      - name: Deploy to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
          force_orphan: true
          exclude_assets: ''
