name: documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        document:
          - pos
          - stakeholder
          - methodology
          - wbs
          - business_case
          - pds
          - project_charter
          - rbs
          - sow
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Note: bumped to v4 (latest), v6 does not exist yet

      - name: Configure Git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: quarkdown-labs/setup-quarkdown@v1

      - name: Build ${{ matrix.document }}
        run: quarkdown c documentation/${{ matrix.document }}/main.qd --pdf --out
          ./documentation/out --out-name ${{ matrix.document }}

      # Upload each PDF to the runner network so the deploy job can access them
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.document }}-pdf
          path: ./documentation/out/${{ matrix.document }}.pdf

  deploy-documentation:
    needs: build-documentation # Waits for all matrix jobs to finish successfully
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all PDFs
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-pdfs

      - name: Consolidate PDFs
        run: |
          mkdir -p ./documentation/out
          # The download step creates subdirectories for each artifact name.
          # This command flattens them back into the /out/ directory.
          find ./downloaded-pdfs -name "*.pdf" -exec mv {} ./documentation/out/ \;

      - name: Deploy to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
          force_orphan: true
          exclude_assets: ''
